# Generated by Django 4.1.13 on 2024-04-28 15:43

import ckeditor.fields
from django.db import migrations, models
import services.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma vaxtı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə vaxtı')),
                ('slug', services.custom_fields.CustomSlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=300, verbose_name='Kateqoriyanın adı')),
            ],
            options={
                'verbose_name': 'Məhsul kateqoriyası',
                'verbose_name_plural': 'Məhsul kateqoriyaları',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma vaxtı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə vaxtı')),
                ('slug', services.custom_fields.CustomSlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=300, verbose_name='Başlıq')),
                ('price', models.FloatField(default=0, verbose_name='Məhsulun qiyməti')),
                ('category', models.PositiveIntegerField(verbose_name='Məhsulun Kateqoriyası')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Məhsul haqqında mətn')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
            },
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
